# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0
name: hashicorp/field-workshops-terraform/deploy-terraform-cloud-azure-v2
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'instruqt-tracks/terraform-cloud-azure-v2/**'
permissions:
  contents: read
jobs:
  deploy-track:
    uses: ./.github/workflows/instruqt-track-deploy.yml
    with:
      working_directory: "instruqt-tracks/terraform-cloud-azure-v2"
      INSTRUQT_CLI_URI: ${{ vars.INSTRUQT_CLI_URI }}
    secrets:
      INSTRUQT_TOKEN: ${{ secrets.INSTRUQT_TOKEN }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
